config/routes.rb
Rails.application.routes.draw do
  	

  get 'administrar/permisos'

  resources :muestreos
  get 'control/permisos'
  post 'administrar/ascender', :as => :ascender_usuario
  post 'administrar/descender', :as => :descender_usuario
  devise_for :users
  match 'users/:id' => 'administrar#destroy', :via => :delete, :as => :admin_destroy_user
  resources :empleados
  resources :proyectos
  resources :operacions
  resources :observacions
  resources :tareas
  resources :muestras
  get "index/home"

  root 'index#home'

  #devise_for :members, :controllers => { :registration => "registration" }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/empleado.rb
class Empleado < ApplicationRecord
end

app/models/muestra.rb
class Muestra < ApplicationRecord
	belongs_to :muestreo
	has_one :empleado
	has_one :operacion
	has_one :tarea
end

app/models/muestreo.rb
class Muestreo < ApplicationRecord
	belongs_to :proyecto
	has_many :muestras
end

app/models/observacion.rb
class Observacion < ApplicationRecord
	belongs_to :muestreo
end

app/models/operacion.rb
class Operacion < ApplicationRecord
	belongs_to :proyecto
end

app/models/proyecto.rb
class Proyecto < ApplicationRecord
	has_many :muestreos
	has_many :empleados
end

app/models/schedule.rb
class Schedule < ApplicationRecord
end

app/models/tarea.rb
class Tarea < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/proyectos_controller.rb
class ProyectosController < ApplicationController
  before_action :set_proyecto, only: [:show, :edit, :update, :destroy]

  # GET /proyectos
  # GET /proyectos.json
  def index
    @proyectos = Proyecto.all
    @can_create = false
    if current_user.permission > 0
      @can_create = true
    end
  end

  # GET /proyectos/1
  # GET /proyectos/1.json
  def show
    
  end

  # GET /proyectos/new
  def new
    @proyecto = Proyecto.new
  end

  # GET /proyectos/1/edit
  def edit
  end

  # POST /proyectos
  # POST /proyectos.json
  def create
    @proyecto = Proyecto.new(proyecto_params)

    respond_to do |format|
      if @proyecto.save
        format.html { redirect_to @proyecto, notice: 'Proyecto was successfully created.' }
        format.json { render :show, status: :created, location: @proyecto }
      else
        format.html { render :new }
        format.json { render json: @proyecto.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /proyectos/1
  # PATCH/PUT /proyectos/1.json
  def update
    respond_to do |format|
      if @proyecto.update(proyecto_params)
        format.html { redirect_to @proyecto, notice: 'Proyecto was successfully updated.' }
        format.json { render :show, status: :ok, location: @proyecto }
      else
        format.html { render :edit }
        format.json { render json: @proyecto.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /proyectos/1
  # DELETE /proyectos/1.json
  def destroy
    @proyecto.destroy
    respond_to do |format|
      format.html { redirect_to proyectos_url, notice: 'Proyecto was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_proyecto
      @proyecto = Proyecto.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def proyecto_params
      params.require(:proyecto).permit(:fecha_inicio, :descripcion)
    end
end

app/helpers/administrar_helper.rb
module AdministrarHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/control_helper.rb
module ControlHelper
end

app/helpers/empleados_helper.rb
module EmpleadosHelper
end

app/helpers/index_helper.rb
module IndexHelper
end

app/helpers/muestras_helper.rb
module MuestrasHelper
end

app/helpers/muestreos_helper.rb
module MuestreosHelper
end

app/helpers/observacions_helper.rb
module ObservacionsHelper
end

app/helpers/operacions_helper.rb
module OperacionsHelper
end

app/helpers/proyectos_helper.rb
module ProyectosHelper
end

app/helpers/registration_helper.rb
module RegistrationHelper
end

app/helpers/tareas_helper.rb
module TareasHelper
end

app/views/proyectos/_form.html.erb
<%= form_with(model: proyecto, local: true) do |form| %>
  <% if proyecto.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(proyecto.errors.count, "error") %> prohibited this proyecto from being saved:</h2>

      <ul>
      <% proyecto.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :fecha_inicio %>
    <%= form.datetime_select :fecha_inicio, id: :proyecto_fecha_inicio %>
  </div>

  <div class="field">
    <%= form.label :descripcion %>
    <%= form.text_area :descripcion, id: :proyecto_descripcion %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/proyectos/edit.html.erb
<h1>Editing Proyecto</h1>

<%= render 'form', proyecto: @proyecto %>

<%= link_to 'Show', @proyecto %> |
<%= link_to 'Back', proyectos_path %>

app/views/proyectos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Proyectos</h1>

<table>
  <thead>
    <tr>
      <th>Fecha inicio</th>
      <th>Descripcion</th>
      <th colspan="3"></th>
    </tr> 
  </thead>

  <tbody>
    <% @proyectos.each do |proyecto| %>
      <tr>
        <td><%= proyecto.fecha_inicio %></td>
        <td><%= proyecto.descripcion %></td>
        <% if(current_user.permission > 0) %>
        <td><%= link_to 'Show', proyecto %></td>
        <td><%= link_to 'Edit', edit_proyecto_path(proyecto) %></td>
        <td><%= link_to 'Destroy', proyecto, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
        <td><%= link_to 'Muestreos', muestreos_path(:proyecto_id => proyecto.id, :from_proyecto => true) %></td>
        <% if @can_create == true %>
        <<td><%= link_to 'Empleados', empleados_path(:proyecto_id => proyecto.id, :from_proyecto => true) %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<% if @can_create == true %>
<%= link_to 'Nuevo Proyecto', new_proyecto_path%>
<%= link_to 'Administrar Tareas', tareas_path%>
<%= link_to 'Administrar Usuarios', "administrar/permisos"%>
<% end %>

app/views/proyectos/new.html.erb
<h1>New Proyecto</h1>

<%= render 'form', proyecto: @proyecto %>

<%= link_to 'Back', proyectos_path %>

app/views/proyectos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Fecha inicio:</strong>
  <%= @proyecto.fecha_inicio %>
</p>

<p>
  <strong>Descripcion:</strong>
  <%= @proyecto.descripcion %>
</p>


<%= link_to 'Edit', edit_proyecto_path(@proyecto) %> |
<%= link_to 'Back', proyectos_path %>