config/routes.rb
Rails.application.routes.draw do
  	

  get 'administrar/permisos'

  resources :muestreos
  get 'control/permisos'
  post 'administrar/ascender', :as => :ascender_usuario
  post 'administrar/descender', :as => :descender_usuario
  devise_for :users
  match 'users/:id' => 'administrar#destroy', :via => :delete, :as => :admin_destroy_user
  resources :empleados
  resources :proyectos
  resources :operacions
  resources :observacions
  resources :tareas
  resources :muestras
  get "index/home"

  root 'index#home'

  #devise_for :members, :controllers => { :registration => "registration" }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/empleado.rb
class Empleado < ApplicationRecord
end

app/models/muestra.rb
class Muestra < ApplicationRecord
	belongs_to :muestreo
	has_one :empleado
	has_one :operacion
	has_one :tarea
end

app/models/muestreo.rb
class Muestreo < ApplicationRecord
	belongs_to :proyecto
	has_many :muestras
end

app/models/observacion.rb
class Observacion < ApplicationRecord
	belongs_to :muestreo
end

app/models/operacion.rb
class Operacion < ApplicationRecord
	belongs_to :proyecto
end

app/models/proyecto.rb
class Proyecto < ApplicationRecord
	has_many :muestreos
	has_many :empleados
end

app/models/schedule.rb
class Schedule < ApplicationRecord
end

app/models/tarea.rb
class Tarea < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/muestras_controller.rb
class MuestrasController < ApplicationController
  before_action :set_muestra, only: [:show, :edit, :update, :destroy]

  # GET /muestras
  # GET /muestras.json
  def index
    
    if params[:from_muestreo]
        session[:muestreo_id] = params[:muestreo_id]
    end
    @muestras = Muestra.where(muestreo_id: session[:muestreo_id]).all
    @muest_id = session[:muestreo_id].to_i
    #@empleados = Empleado.where(proyecto_id: session[:proyecto_id].to_i).all
    #puts(@proy_id)
    @can_create = false
    if current_user.permission > 0
      @can_create = true
    end
    if(@muestras == nil)
        @muestras = {}
    end

    @horarios = Schedule.where(muestreo_id: session[:muestreo_id]).all
    if(@horarios == nil)
      @horarios = {}
    end
     @observaciones = Observacion.where(muestreo_id: session[:muestreo_id]).all
    if(@observaciones == nil)
      @observaciones = {}
    end
    
  end

  # GET /muestras/1
  # GET /muestras/1.json
  def show
     muestra = Muestra.find(params[:id])
     @empleado = Empleado.find(muestra.empleado_id)
     @tarea = Tarea.find(muestra.tarea_id)
  end

  # GET /muestras/new
  def new
    @muestra = Muestra.new
    @proy_id = session[:proyecto_id].to_i
  end

  # GET /muestras/1/edit
  def edit
  end

  # POST /muestras
  # POST /muestras.json
  def create

    local_params = muestra_params;
    local_params[:muestreo_id] = session[:muestreo_id]
    @muestra = Muestra.new(local_params)
    #render inline: "<%= @local_params %>"

    respond_to do |format|
      if @muestra.save
        format.html { redirect_to @muestra, notice: 'Muestra was successfully created.' }
        format.json { render :show, status: :created, location: @muestra }
      else
        format.html { render :new }
        format.json { render json: @muestra.errors, status: :unprocessable_entity }
      end
    end

  end

  # PATCH/PUT /muestras/1
  # PATCH/PUT /muestras/1.json
  def update
    respond_to do |format|
      if @muestra.update(muestra_params)
        format.html { redirect_to @muestra, notice: 'Muestra was successfully updated.' }
        format.json { render :show, status: :ok, location: @muestra }
      else
        format.html { render :edit }
        format.json { render json: @muestra.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /muestras/1
  # DELETE /muestras/1.json
  def destroy
    @muestra.destroy
    respond_to do |format|
      format.html { redirect_to muestras_url, notice: 'Muestra was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_muestra
      @muestra = Muestra.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def muestra_params
      params.require(:muestra).permit(:hora, :humedad, :temperatura,:tarea_id,:empleado_id)
    end
end

app/helpers/administrar_helper.rb
module AdministrarHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/control_helper.rb
module ControlHelper
end

app/helpers/empleados_helper.rb
module EmpleadosHelper
end

app/helpers/index_helper.rb
module IndexHelper
end

app/helpers/muestras_helper.rb
module MuestrasHelper
end

app/helpers/muestreos_helper.rb
module MuestreosHelper
end

app/helpers/observacions_helper.rb
module ObservacionsHelper
end

app/helpers/operacions_helper.rb
module OperacionsHelper
end

app/helpers/proyectos_helper.rb
module ProyectosHelper
end

app/helpers/registration_helper.rb
module RegistrationHelper
end

app/helpers/tareas_helper.rb
module TareasHelper
end

app/views/muestras/_form.html.erb
<%= form_with(model: muestra, local: true) do |form| %>
  <% if muestra.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(muestra.errors.count, "error") %> prohibited this muestra from being saved:</h2>

      <ul>
      <% muestra.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :hora %>
    <%= form.datetime_select :hora, id: :muestra_hora %>
  </div>

  <div class="field">
    <%= form.label :humedad %>
    <%= form.text_field :humedad, id: :muestra_humedad %>
  </div>

  <div class="field">
    <%= form.label :temperatura %>
    <%= form.text_field :temperatura, id: :muestra_temperatura %>
  </div>
  <div>
    <%= form.label :tarea %>
    <%= form.collection_select :tarea_id, Tarea.all, :id, :nombre%>
  </div>
  <div>
    <%= form.label :empleado %>
    <%= form.collection_select :empleado_id, Empleado.where(proyecto_id: @proy_id).all, :id, :nombre %>
  </div>
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/muestras/edit.html.erb
<h1>Editing Muestra</h1>

<%= render 'form', muestra: @muestra %>

<%= link_to 'Show', @muestra %> |
<%= link_to 'Back', muestras_path %>

app/views/muestras/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Muestras</h1>

<table>
  <thead>
    <tr>
      <th>Hora</th>
      <th>Humedad</th>
      <th>Temperatura</th>
      <th>Tarea</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @muestras.each do |muestra| %>
    <% if muestra.muestreo_id == @muest_id %>
      <tr>
        <td><%= muestra.hora %></td>
        <td><%= muestra.humedad %></td>
        <td><%= muestra.temperatura %></td>
        <td><%= Tarea.find(muestra.tarea_id).nombre %></td>
        <% if(@can_create) %>
        <td><%= link_to 'mostrar mas', muestra %></td>
        <td><%= link_to 'Edit', edit_muestra_path(muestra) %></td>
        <td><%= link_to 'Destroy', muestra, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
    <% end %>
  </tbody>
</table>

<br>
<%= link_to 'Nueva Muestra', new_muestra_path %>
<br>
<p>
  <h1>Horas de muestra</h1>
</p>
<table>
  <thead>
  <tr>
  <th> Dia </th>
  <th> Hora </th>
  </tr>
  </thead>
<% @horarios.each do |sc| %>
  <tbody>
  <tr>
    <% if(Time.now - sc.hora < 0) %>
    <td><%= sc.hora.strftime('%F') %></td>
    <td><%= sc.hora.strftime('%I:%M:%S %p') %></td>
    <% end %>
  </tr>
  
  </tbody>
<% end %>
</table>
<br>

<p>
  <h1>Observaciones</h1>
</p>

<table>
  <thead>
  <tr>
  <th> Dia </th>
  <th> Hora </th>
  <th> Datos </th>
  <th></th>
  </tr>
  </thead>
<% @observaciones.each do |ob| %>
  <tbody>
  <tr>
    <td><%= ob.created_at.strftime('%F') %></td>
    <td><%= ob.created_at.strftime('%I:%M:%S %p') %></td>
    <td><%= ob.descripcion%></td>
    <td><%= link_to 'Show', ob %></td>
  </tr>
  
  </tbody>
<% end %>
</table>
<br>


<%= link_to 'Nueva Observacion', new_observacion_path %>
<%= link_to 'Volver', muestreos_path %>

app/views/muestras/new.html.erb
<h1>New Muestra</h1>

<%= render 'form', muestra: @muestra %>

<%= link_to 'Back', muestras_path %>

app/views/muestras/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Hora:</strong>
  <%= @muestra.hora %>
</p>

<p>
  <strong>Humedad:</strong>
  <%= @muestra.humedad %>
</p>

<p>
  <strong>Temperatura:</strong>
  <%= @muestra.temperatura %>
</p>

<p>
  <strong>Empleado:</strong>
  <%= @empleado.nombre%>
</p>

<p>
  <strong>Tarea:</strong>
  <%= @tarea.nombre%>
</p>
<p>
	<strong>Productividad:</strong>
	<% if(@tarea.pro_type == 0)%>
	<%= "Improductiva" %>
	<% elsif(@tarea.pro_type == 1)%>
	<%= "Colaborativa" %>
	<% else %>
	<%= "Productiva" %>
	<% end %>
</p>

<%= link_to 'Edit', edit_muestra_path(@muestra) %> |
<%= link_to 'Back', muestras_path %>