config/routes.rb
Rails.application.routes.draw do
  	

  get 'administrar/permisos'

  resources :muestreos
  get 'control/permisos'
  post 'administrar/ascender', :as => :ascender_usuario
  post 'administrar/descender', :as => :descender_usuario
  devise_for :users
  match 'users/:id' => 'administrar#destroy', :via => :delete, :as => :admin_destroy_user
  resources :empleados
  resources :proyectos
  resources :operacions
  resources :observacions
  resources :tareas
  resources :muestras
  get "index/home"

  root 'index#home'

  #devise_for :members, :controllers => { :registration => "registration" }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/empleado.rb
class Empleado < ApplicationRecord
end

app/models/muestra.rb
class Muestra < ApplicationRecord
	belongs_to :muestreo
	has_one :empleado
	has_one :operacion
	has_one :tarea
end

app/models/muestreo.rb
class Muestreo < ApplicationRecord
	belongs_to :proyecto
	has_many :muestras
end

app/models/observacion.rb
class Observacion < ApplicationRecord
	belongs_to :muestreo
end

app/models/operacion.rb
class Operacion < ApplicationRecord
	belongs_to :proyecto
end

app/models/proyecto.rb
class Proyecto < ApplicationRecord
	has_many :muestreos
	has_many :empleados
end

app/models/schedule.rb
class Schedule < ApplicationRecord
end

app/models/tarea.rb
class Tarea < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/administrar_controller.rb
class AdministrarController < ApplicationController
  def permisos
  @usuarios = User.all
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy

    if @user.destroy
        redirect_back(fallback_location: root_path,notice: "User deleted.")
    end
  end
  #convierte al usuario en administrador
  def ascender
  	usuario = User.find(params[:usuario_id].to_i)
  	#puts(params[:usuario_id].to_i)
  	usuario.update_attribute(:permission, 1)
  	redirect_back(fallback_location: root_path)
  end
  #convierte al usuario en usuario comun
  def descender
  	usuario = User.find(params[:usuario_id])
  	usuario.update_attribute(:permission, 0)
  	redirect_back(fallback_location: root_path)
  end

end

app/helpers/administrar_helper.rb
module AdministrarHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/control_helper.rb
module ControlHelper
end

app/helpers/empleados_helper.rb
module EmpleadosHelper
end

app/helpers/index_helper.rb
module IndexHelper
end

app/helpers/muestras_helper.rb
module MuestrasHelper
end

app/helpers/muestreos_helper.rb
module MuestreosHelper
end

app/helpers/observacions_helper.rb
module ObservacionsHelper
end

app/helpers/operacions_helper.rb
module OperacionsHelper
end

app/helpers/proyectos_helper.rb
module ProyectosHelper
end

app/helpers/tareas_helper.rb
module TareasHelper
end

app/views/administrar/permisos.html.erb
<p id="notice"><%= notice %></p>

<h1>Administrar Usuarios</h1>

<table>
  <thead>
    <tr>
      <th>Email</th>
      <th>nombre</th>
      <th colspan="3"></th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @usuarios.each do |usuario| %>
      <tr>
        <td><%= usuario.email %></td>
        <td><%= usuario.name %></td>
        <td><%= link_to 'Destroy', admin_destroy_user_path(usuario), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      	<td><% if (usuario.permission < 1)%>
      		<%= link_to 'Ascender', ascender_usuario_path(:usuario_id =>usuario.id), method: :update, data: { confirm: 'Are you sure?' } %>
      		<% else %>
      		<%= link_to 'Descender', descender_usuario_path(:usuario_id =>usuario.id), method: :update, data: { confirm: 'Are you sure?' } %>
      		<% end %>
      		</td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Nuevo Empleado', new_empleado_path %>
<%= link_to 'Volver', proyectos_path %>