config/routes.rb
Rails.application.routes.draw do
  	

  get 'administrar/permisos'

  resources :muestreos
  get 'control/permisos'
  post 'administrar/ascender', :as => :ascender_usuario
  post 'administrar/descender', :as => :descender_usuario
  devise_for :users
  match 'users/:id' => 'administrar#destroy', :via => :delete, :as => :admin_destroy_user
  resources :empleados
  resources :proyectos
  resources :operacions
  resources :observacions
  resources :tareas
  resources :muestras
  get "index/home"

  root 'index#home'

  #devise_for :members, :controllers => { :registration => "registration" }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/empleado.rb
class Empleado < ApplicationRecord
end

app/models/muestra.rb
class Muestra < ApplicationRecord
	belongs_to :muestreo
	has_one :empleado
	has_one :operacion
	has_one :tarea
end

app/models/muestreo.rb
class Muestreo < ApplicationRecord
	belongs_to :proyecto
	has_many :muestras
end

app/models/observacion.rb
class Observacion < ApplicationRecord
	belongs_to :muestreo
end

app/models/operacion.rb
class Operacion < ApplicationRecord
	belongs_to :proyecto
end

app/models/proyecto.rb
class Proyecto < ApplicationRecord
	has_many :muestreos
	has_many :empleados
end

app/models/schedule.rb
class Schedule < ApplicationRecord
end

app/models/tarea.rb
class Tarea < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/muestreos_controller.rb
class MuestreosController < ApplicationController
  before_action :set_muestreo, only: [:show, :edit, :update, :destroy]

  # GET /muestreos
  # GET /muestreos.json
  def index
    

    if params[:from_proyecto]
        session[:proyecto_id] = params[:proyecto_id]
    end
    proy_id = session[:proyecto_id].to_i
    @muestreos = Muestreo.where(proyecto_id: proy_id).all

    if(@muestreos == nil)
        @muestreos = {}
    end
  end

  # GET /muestreos/1
  # GET /muestreos/1.json
  def show
    @horarios = Schedule.where(muestreo_id: @muestreo.id).all
    if(@horarios == nil)
      @horarios = {}
    end
  end

  # GET /muestreos/new
  def new
    @muestreo = Muestreo.new
  end

  # GET /muestreos/1/edit
  def edit
  end

  # POST /muestreos
  # POST /muestreos.json
  def create

    local_params = muestreo_params
    local_params[:proyecto_id] = session[:proyecto_id]
    
    @muestreo = Muestreo.new(local_params)
    #@id = local_params
    #render inline: "<%= @id %> "
    respond_to do |format|
      if @muestreo.save
        total = local_params[:meta].to_i
        time = Time.now
        minimo = local_params[:minimo].to_i
        maximo = local_params[:maximo].to_i
        #puts total
        #puts local_params
        for i in 0..total
            Schedule.create({muestreo_id: @muestreo.id, hora: time})
            time = time + (minimo + rand((maximo - minimo).abs)).minutes
        end
        format.html { redirect_to @muestreo, notice: 'Muestreo was successfully created.' }
        format.json { render :show, status: :created, location: @muestreo }
      else
        format.html { render :new }
        format.json { render json: @muestreo.errors, status: :unprocessable_entity }
      end

    end
  end

  # PATCH/PUT /muestreos/1
  # PATCH/PUT /muestreos/1.json
  def update

    local_params = muestreo_params
    local_params[:proyecto_id] = session[:proyecto_id]
    respond_to do |format|
      if @muestreo.update(local_params)
        format.html { redirect_to @muestreo, notice: 'Muestreo was successfully updated.' }
        format.json { render :show, status: :ok, location: @muestreo }
      else
        format.html { render :edit }
        format.json { render json: @muestreo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /muestreos/1
  # DELETE /muestreos/1.json
  def destroy
    Muestra.where(muestreo_id: @muestreo.id).delete_all
    Schedule.where(muestreo_id: @muestreo.id).delete_all
    @muestreo.destroy
    respond_to do |format|
      format.html { redirect_to muestreos_url, notice: 'Muestreo was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_muestreo
      @muestreo = Muestreo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def muestreo_params
      params.require(:muestreo).permit(:fecha_inicio, :fecha_fin, :meta, :proyecto_id,:minimo,:maximo)
    end
end

app/helpers/administrar_helper.rb
module AdministrarHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/control_helper.rb
module ControlHelper
end

app/helpers/empleados_helper.rb
module EmpleadosHelper
end

app/helpers/index_helper.rb
module IndexHelper
end

app/helpers/muestras_helper.rb
module MuestrasHelper
end

app/helpers/muestreos_helper.rb
module MuestreosHelper
end

app/helpers/observacions_helper.rb
module ObservacionsHelper
end

app/helpers/operacions_helper.rb
module OperacionsHelper
end

app/helpers/proyectos_helper.rb
module ProyectosHelper
end

app/helpers/registration_helper.rb
module RegistrationHelper
end

app/helpers/tareas_helper.rb
module TareasHelper
end

app/views/muestreos/_form.html.erb
<%= form_with(model: muestreo, local: true) do |form| %>
  <% if muestreo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(muestreo.errors.count, "error") %> prohibited this muestreo from being saved:</h2>

      <ul>
      <% muestreo.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :fecha_inicio %>
    <%= form.datetime_select :fecha_inicio, id: :muestreo_fecha_inicio %>
  </div>

  <div class="field">
    <%= form.label :fecha_fin %>
    <%= form.datetime_select :fecha_fin, id: :muestreo_fecha_fin %>
  </div>

  <div class="field">
    <%= form.label :meta %>
    <%= form.number_field :meta, id: :muestreo_meta %>
  </div>
  <div class="field">
    <%= form.label :minimo_intervalo_minutos %>
    <%= form.number_field :minimo, id: :muestro_minimo %>
  </div>
  <div class="field">
    <%= form.label :maximo_intervalo_minutos %>
    <%= form.number_field :maximo, id: :muestro_maximo %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/muestreos/edit.html.erb
<h1>Editing Muestreo</h1>

<%= render 'form', muestreo: @muestreo %>

<%= link_to 'Show', @muestreo %> |
<%= link_to 'Back', muestreos_path %>

app/views/muestreos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Muestreos</h1>
<table>
  <thead>
    <tr>
      <th>Fecha inicio</th>
      <th>Fecha fin</th>
      <th>Meta</th>
      <th>Proyecto</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @muestreos.each do |muestreo| %>
      <tr>
        <td><%= muestreo.fecha_inicio %></td>
        <td><%= muestreo.fecha_fin %></td>
        <td><%= muestreo.meta %></td>
        <td><%= muestreo.proyecto_id %></td>
        <% if(current_user.permission > 0) %>
        <td><%= link_to 'Show', muestreo %></td>
        <td><%= link_to 'Edit', edit_muestreo_path(muestreo) %></td>
        <td><%= link_to 'Destroy', muestreo, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
        <td><%= link_to 'Muestras', muestras_path(muestreo_id: muestreo.id, from_muestreo: true) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Nuevo Muestreo', new_muestreo_path %>

<%= link_to 'Volver', proyectos_path %>

app/views/muestreos/new.html.erb
<h1>New Muestreo</h1>

<%= render 'form', muestreo: @muestreo %>

<%= link_to 'Back', muestreos_path %>

app/views/muestreos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Fecha inicio:</strong>
  <%= @muestreo.fecha_inicio %>
</p>

<p>
  <strong>Fecha fin:</strong>
  <%= @muestreo.fecha_fin %>
</p>

<p>
  <strong>Meta:</strong>
  <%= @muestreo.meta %>
</p>

<p>
  <strong>Proyecto:</strong>
  <%= @muestreo.proyecto_id %>
</p>

<p>
	<strong>Horas de muestra</strong>
</p>
<table>
	<thead>
	<tr>
	<th> Dia </th>
	<th> Hora </th>
	</tr>
	</thead>
<% @horarios.each do |sc| %>
	<tbody>
	<tr>
		<td><%= sc.hora.strftime('%F') %></td>
		<td><%= sc.hora.strftime('%I:%M:%S %p') %></td>
	</tr>
	
	</tbody>
<% end %>
</table>
<br>
<%= link_to 'Edit', edit_muestreo_path(@muestreo) %> |
<%= link_to 'Back', muestreos_path %>